const Theme = {
    light:{
        theme: "light",
         color: "black",
         background: "white",
         menuBackground: '#fae8e0',
         head: "#f28d82",
         backgroundToilet: "white",
         logoutColor: "red",
         goBack: "#038dca",
         tabColor: "white",
         submitBtn: "#e6697e",
         activeOutColor: "#e6697e",
         day: "gold",
         night: "grey",
         show: "#f28d82",
         backgroundReports: "#f5f5f5",
         reportsChoice: "white",
         check: "#e6697e",
         addMore: "black",
         water: "#a6cbe3",
         bottomBar: "white",
         icon: "#f28d82",
         drop: "white",
         titleReview: "black",
         reviewBorder: "black"

     },
    dark:{
        theme: "dark",
        color: "white",
        background: "#2b2b2b",
        menuBackground: "#ae8647",
        head: "#0d1b2a",
        backgroundToilet: "#a29a9a",
        logoutColor: "#ae8647",
        goBack: "#ae8647",
        tabColor: "black",
        submitBtn: "#ae8647",
        activeOutColor: "#ae8647",
        day: "grey",
        night: "gold",
        show: "grey",
        backgroundReports: "#2b2b2b",
        reportsChoice: "#bcbcbc",
        check: "gold",
        addMore: "#d7b604",
        water: "#6040bd",
        bottomBar: "#242526",
        icon: "#ccaa55",
        drop: "#ccaa55",
        titleReview: "#ccaa55",
        reviewBorder: "grey"
    },
};
export default Theme;